### ISSUE TITLE
Exceptions when switching channels from the channel list

### ISSUE THREAD

**Issue by libertylocked** [LibertyLocked/NetRadio#3]
This occurs from time to time, seems random. Maybe a check ShoutcastPlayer class?
Will look into this issue.

Seems to work okay if the stream is stopped before channel is switched.

**Comment by JonTheBurger** [comment]
Is it
NAudio.MmException: AcmNotPossible calling acmStreamConverrt 
    at NAudio.MmException.Try(MmResult result, String function)
    at NAudio.Wave.Compression.AcmStreamHeader.Convert(Int32bytesToConvert, Int32& sourceBytesConverted
    at NAudio.Wave.AcmMp3FrameDecompressor.DecompressFrame(Mp3Frame frame, Byte[] dest, Int32 destOffset)
    at RadioPlayer.ShoutcastPlayer.StreamMp3(Object state)
    in <Path>/NetRadio/RadioPlayer/ShoutcastPlayer.cs:line 271
    at RadioPlayer.ShoutcastPlayer.<>c__DisplayClass2.<StartPlayback>b__0(Object state
    in <Path>/NetRadio/RadioPlayer/ShoutcastPlayer.cs:line 67

**Comment by libertylocked** [comment]
I believe so, but this exception does not occur if player is stopped first.

**Comment by JonTheBurger** [comment]
Is there a reason we don't want to just turn off the stream when switching between channels?

**Comment by libertylocked** [comment]
The current implementation is already like that. It calls player.StopPlayback() when switching.
